package restaurant;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author 96654
 */
public class CustomerLogin extends javax.swing.JFrame {

    /**
     * Creates new form CustomerLogin
     */
    Connection con;
    public static int id;
    
    public CustomerLogin() 
    {
        super("Login");
        initComponents();
        setIconImage();
        
        try 
        {
            con=DriverManager.getConnection(Restaurant.DATABASE_URL,Restaurant.USER,Restaurant.PASS);
             
        }
        catch (SQLException ex)                                
        {
            JOptionPane.showMessageDialog(null, ex, "Failed", 2);
        } 
    }
    
    private void setIconImage() 
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustLogin_Panel = new javax.swing.JPanel();
        CustLogin_Label = new javax.swing.JLabel();
        CustUsername_Label = new javax.swing.JLabel();
        CustUser_TextField = new javax.swing.JTextField();
        CustPassword_Label = new javax.swing.JLabel();
        Cust_EnterButton = new javax.swing.JButton();
        Cust_BackButton = new javax.swing.JButton();
        CustAccount_Label = new javax.swing.JLabel();
        CustSignUp_Button = new javax.swing.JButton();
        CustPassword_PasswordField = new javax.swing.JPasswordField();
        CustLogin_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CustLogin_Panel.setLayout(null);

        CustLogin_Label.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        CustLogin_Label.setText("Customer login");
        CustLogin_Panel.add(CustLogin_Label);
        CustLogin_Label.setBounds(40, 20, 240, 50);

        CustUsername_Label.setFont(new java.awt.Font("Perpetua Titling MT", 1, 16)); // NOI18N
        CustUsername_Label.setText("username");
        CustLogin_Panel.add(CustUsername_Label);
        CustUsername_Label.setBounds(20, 120, 170, 30);
        CustLogin_Panel.add(CustUser_TextField);
        CustUser_TextField.setBounds(40, 150, 250, 30);

        CustPassword_Label.setFont(new java.awt.Font("Perpetua Titling MT", 1, 16)); // NOI18N
        CustPassword_Label.setText("password");
        CustLogin_Panel.add(CustPassword_Label);
        CustPassword_Label.setBounds(20, 200, 100, 30);

        Cust_EnterButton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 16)); // NOI18N
        Cust_EnterButton.setText("enter");
        Cust_EnterButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Cust_EnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cust_EnterButtonActionPerformed(evt);
            }
        });
        CustLogin_Panel.add(Cust_EnterButton);
        Cust_EnterButton.setBounds(60, 380, 100, 30);

        Cust_BackButton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 16)); // NOI18N
        Cust_BackButton.setText("back");
        Cust_BackButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Cust_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cust_BackButtonActionPerformed(evt);
            }
        });
        CustLogin_Panel.add(Cust_BackButton);
        Cust_BackButton.setBounds(180, 380, 100, 30);

        CustAccount_Label.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        CustAccount_Label.setText("Don't have an account?");
        CustLogin_Panel.add(CustAccount_Label);
        CustAccount_Label.setBounds(50, 290, 230, 20);

        CustSignUp_Button.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        CustSignUp_Button.setText("Sign up");
        CustSignUp_Button.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        CustSignUp_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustSignUp_ButtonActionPerformed(evt);
            }
        });
        CustLogin_Panel.add(CustSignUp_Button);
        CustSignUp_Button.setBounds(120, 310, 90, 30);
        CustLogin_Panel.add(CustPassword_PasswordField);
        CustPassword_PasswordField.setBounds(40, 230, 250, 30);

        CustLogin_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/Images/Background logo.jpg"))); // NOI18N
        CustLogin_Panel.add(CustLogin_Background);
        CustLogin_Background.setBounds(0, 0, 330, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CustLogin_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CustLogin_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cust_EnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cust_EnterButtonActionPerformed
           
        PreparedStatement ps;
        ResultSet rs;
        String QUERY;
        String username = CustUser_TextField.getText();
        String password = String.valueOf(CustPassword_PasswordField.getPassword());
        
        if (username.equals("") || password.equals("")) 
        {
            JOptionPane.showMessageDialog(null, "Please fill all data", "Error", 2);
        } 
        else 
        {
            try 
            {
                QUERY = "SELECT * FROM Customer WHERE CUsername =? AND CPassword =?";

                ps = con.prepareStatement(QUERY);

                ps.setString(1, username);
                ps.setString(2, password);

                rs = ps.executeQuery();

                if (rs.next()) 
                {
                    id = rs.getInt(1);
                    CustHomepage frame = new CustHomepage();
                    frame.setLocationRelativeTo(null);
                    frame.setVisible(true);
                    this.setVisible(false);
                } 
                else 
                {
                    JOptionPane.showMessageDialog(null, "Unregistered user", "Login Failed", 2);
                }

            }//try
            
            catch (SQLException ex) 
            {
                JOptionPane.showMessageDialog(null, ex, "Failed", 2);
            }
        }
    }//GEN-LAST:event_Cust_EnterButtonActionPerformed

    private void Cust_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cust_BackButtonActionPerformed
      
        try 
        {
            con.close();
        } 
        catch (SQLException ex) 
        {
            ex.printStackTrace();
        }
        
        Homepage frame = new Homepage();

        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Cust_BackButtonActionPerformed

    private void CustSignUp_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustSignUp_ButtonActionPerformed

        try 
        {
            con.close();
        } 
        catch (SQLException ex) 
        {
            ex.printStackTrace();
        }
        SignUp frame = new SignUp();

        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CustSignUp_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustAccount_Label;
    private javax.swing.JLabel CustLogin_Background;
    private javax.swing.JLabel CustLogin_Label;
    private javax.swing.JPanel CustLogin_Panel;
    private javax.swing.JLabel CustPassword_Label;
    private javax.swing.JPasswordField CustPassword_PasswordField;
    private javax.swing.JButton CustSignUp_Button;
    private javax.swing.JTextField CustUser_TextField;
    private javax.swing.JLabel CustUsername_Label;
    private javax.swing.JButton Cust_BackButton;
    private javax.swing.JButton Cust_EnterButton;
    // End of variables declaration//GEN-END:variables
}
