/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant;

import java.awt.Toolkit;

/**
 *
 * @author 96654
 */
public class EmpHomepage extends javax.swing.JFrame {

    /**
     * Creates new form EmpAdd
     */
    public EmpHomepage() {
        super("Employee Homepage");
        initComponents();
        setIconImage();
    }
    private void setIconImage() 
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmpHomepage_Panel = new javax.swing.JPanel();
        EmpHomepage_Label1 = new javax.swing.JLabel();
        EmpHomepage_modifyS = new javax.swing.JButton();
        EmpHomepage_Label2 = new javax.swing.JLabel();
        EmpHomepage_BackButton = new javax.swing.JButton();
        EmpHomepage_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EmpHomepage_Panel.setLayout(null);

        EmpHomepage_Label1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        EmpHomepage_Label1.setText("What do you want");
        EmpHomepage_Panel.add(EmpHomepage_Label1);
        EmpHomepage_Label1.setBounds(20, 60, 300, 50);

        EmpHomepage_modifyS.setFont(new java.awt.Font("Perpetua Titling MT", 1, 16)); // NOI18N
        EmpHomepage_modifyS.setText("Modify Special Dishes");
        EmpHomepage_modifyS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpHomepage_modifySActionPerformed(evt);
            }
        });
        EmpHomepage_Panel.add(EmpHomepage_modifyS);
        EmpHomepage_modifyS.setBounds(30, 240, 270, 40);

        EmpHomepage_Label2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        EmpHomepage_Label2.setText("to do?");
        EmpHomepage_Panel.add(EmpHomepage_Label2);
        EmpHomepage_Label2.setBounds(110, 90, 100, 50);

        EmpHomepage_BackButton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        EmpHomepage_BackButton.setText("Sign out");
        EmpHomepage_BackButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        EmpHomepage_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpHomepage_BackButtonActionPerformed(evt);
            }
        });
        EmpHomepage_Panel.add(EmpHomepage_BackButton);
        EmpHomepage_BackButton.setBounds(10, 10, 100, 20);

        EmpHomepage_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/Images/Background logo.jpg"))); // NOI18N
        EmpHomepage_Panel.add(EmpHomepage_Background);
        EmpHomepage_Background.setBounds(0, 0, 330, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmpHomepage_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmpHomepage_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmpHomepage_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpHomepage_BackButtonActionPerformed
        // TODO add your handling code here:
        EmployeeLogin frame = new EmployeeLogin();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EmpHomepage_BackButtonActionPerformed

    private void EmpHomepage_modifySActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpHomepage_modifySActionPerformed
        // TODO add your handling code here:
        Spechial_Dishes frame = new Spechial_Dishes();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_EmpHomepage_modifySActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmpHomepage_BackButton;
    private javax.swing.JLabel EmpHomepage_Background;
    private javax.swing.JLabel EmpHomepage_Label1;
    private javax.swing.JLabel EmpHomepage_Label2;
    private javax.swing.JPanel EmpHomepage_Panel;
    private javax.swing.JButton EmpHomepage_modifyS;
    // End of variables declaration//GEN-END:variables
}
