package restaurant;

import java.awt.Toolkit;

public class Homepage extends javax.swing.JFrame {

    
    public Homepage() 
    {
        super("Good Taste Restaurant");
        initComponents();
        setIconImage();
    }
    
    private void setIconImage() 
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Homepage_Panel = new javax.swing.JPanel();
        Homepage_Label1 = new javax.swing.JLabel();
        Homepage_Label2 = new javax.swing.JLabel();
        Homepage_Label3 = new javax.swing.JLabel();
        Homepage_CustLoginButton = new javax.swing.JButton();
        Homepage_EmpLoginButton = new javax.swing.JButton();
        Homepage_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Homepage_Panel.setPreferredSize(new java.awt.Dimension(340, 470));
        Homepage_Panel.setLayout(null);

        Homepage_Label1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 30)); // NOI18N
        Homepage_Label1.setText("Homepage");
        Homepage_Panel.add(Homepage_Label1);
        Homepage_Label1.setBounds(70, 20, 190, 41);

        Homepage_Label2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        Homepage_Label2.setText("Welcome to our");
        Homepage_Panel.add(Homepage_Label2);
        Homepage_Label2.setBounds(50, 150, 240, 36);

        Homepage_Label3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        Homepage_Label3.setText("restaurant");
        Homepage_Panel.add(Homepage_Label3);
        Homepage_Label3.setBounds(90, 190, 170, 40);

        Homepage_CustLoginButton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        Homepage_CustLoginButton.setText("Customer Login");
        Homepage_CustLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Homepage_CustLoginButtonActionPerformed(evt);
            }
        });
        Homepage_Panel.add(Homepage_CustLoginButton);
        Homepage_CustLoginButton.setBounds(80, 320, 180, 41);

        Homepage_EmpLoginButton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        Homepage_EmpLoginButton.setText("Employee Login");
        Homepage_EmpLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Homepage_EmpLoginButtonActionPerformed(evt);
            }
        });
        Homepage_Panel.add(Homepage_EmpLoginButton);
        Homepage_EmpLoginButton.setBounds(80, 370, 180, 41);

        Homepage_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/Images/Background logo.jpg"))); // NOI18N
        Homepage_Panel.add(Homepage_Background);
        Homepage_Background.setBounds(0, 0, 330, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Homepage_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Homepage_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Homepage_CustLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Homepage_CustLoginButtonActionPerformed
       
        CustomerLogin frame = new CustomerLogin();

        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Homepage_CustLoginButtonActionPerformed

    private void Homepage_EmpLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Homepage_EmpLoginButtonActionPerformed
        
        EmployeeLogin frame = new EmployeeLogin();

        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Homepage_EmpLoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Homepage_Background;
    private javax.swing.JButton Homepage_CustLoginButton;
    private javax.swing.JButton Homepage_EmpLoginButton;
    private javax.swing.JLabel Homepage_Label1;
    private javax.swing.JLabel Homepage_Label2;
    private javax.swing.JLabel Homepage_Label3;
    private javax.swing.JPanel Homepage_Panel;
    // End of variables declaration//GEN-END:variables

}
